version: "3"

services: 
    redis:
        image: 
            redis:latest
    postgres-client:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /server/node_modules
            - ./server:/server
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGPASSWORD=postgres_password
            - PGHOST=postgres-client
            - PGPORT=5432
            - PGDATABASE=postgres
        depends_on: 
            - postgres-client
            - redis
    client:
        stdin_open: true
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /react-app/node_modules
            - ./client:/react-app
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /worker/node_modules
            - ./worker:/worker
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - "8000:80"
        depends_on: 
            - api
            - client